import "./globals.css";

export const metadata = {
    title: "Blog",
    description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
